- hosts: terraform-ansible
  tasks:
    - name: Installing Python3, Virtualenv
      apt:
        pkg:
        - python3
        - virtualenv
        update_cache: yes
      become: yes
    - name: Installing dependencies with pip (Django and Django Rest)
      pip:
        virtualenv: /home/ubuntu/venv
        name:
          - django
          - djangorestframework
    - name: Verifing if the project exists
      stat: 
        path: /home/ubuntu/setup/settings.py
      register: project
    - name: Starting Project
      shell: '. /home/ubuntu/venv/bin/activate; django-admin startproject setup /home/ubuntu'
      when: not project.stat.exists
    - name: Changing settings hosts file
      lineinfile: 
        path: /home/ubuntu/setup/settings.py
        regexp: 'ALLOWED_HOSTS'
        line: 'ALLOWED_HOSTS = ["*"]'
        backrefs: yes

